# Import library :

In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns 
import os

# Part 3. Data acquisition and inspection

In [3]:
base_path = os.getcwd()

# Kết nối đến file trong folder data_raw
file_path = os.path.join(base_path, '..', 'data_raw', 'performance.csv')
df = pd.read_csv(file_path)
df.shape

(36468, 5)

In [4]:
df.head(10)

,Student_ID,Subject,Exam_Score,Homework_Completion_%,Teacher_Comments
0,S00396,Arabic,76,90,Possible I large perhaps onto impact pretty ag...
1,S06544,Math,91,100%,Attention very once light speak yeah against c...
2,S01277,Science,92,100%,Something piece phone wish rich these where ca...
3,S00686,English,40,90,Generation same story stand better father perf...
4,S10984,History,57,90,Minute board finally traditional clear result ...
5,S05235,History,91,90,Main magazine consumer country any investment.
6,S00146,English,89,95,Probably specific science memory her stand sin...
7,S11885,English,60,95,Deal feel area matter painting goal both insid...
8,S03222,Science,95,90,South policy with last wide value reach leave ...
9,S01968,Geography,50,95,Card cold imagine analysis here both knowledge.

In [5]:
df.tail(10)

,Student_ID,Subject,Exam_Score,Homework_Completion_%,Teacher_Comments
36458,S02755,Math,69,100%,
36459,S06774,Science,60,-5,
36460,S06301,English,59,100%,Us between real you subject bad cup moment sho...
36461,S01760,Math,74,90,Then member break full sign hundred summer rul...
36462,S07796,History,64,80%,Majority environment score not writer talk.
36463,S09766,Arabic,69,95,Environmental newspaper close story space seas...
36464,S04647,Geography,105,95,Music tend or occur know development see.
36465,S06033,Math,91,80%,Car the choice college consumer before perform...
36466,S00729,English,103,-5,Relate box peace during executive production i...
36467,S09604,English,48,100%,Safe stage know impact guess happen process so...

In [6]:
df.columns

Index(['Student_ID', 'Subject', 'Exam_Score', 'Homework_Completion_%',
       'Teacher_Comments'],
      dtype='object')

In [7]:
df.dtypes

Student_ID               object
Subject                  object
Exam_Score                int64
Homework_Completion_%    object
Teacher_Comments         object
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36468 entries, 0 to 36467
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             36468 non-null  object
 1   Subject                36468 non-null  object
 2   Exam_Score             36468 non-null  int64
 3   Homework_Completion_%  36468 non-null  object
 4   Teacher_Comments       36468 non-null  object
dtypes: int64(1), object(4)
memory usage: 1.4+ MB

In [9]:
df.describe()

         Exam_Score
count  36468.000000
mean      74.964243
std       20.538704
min       40.000000
25%       57.000000
50%       75.000000
75%       93.000000
max      110.000000

In [10]:
df.describe(include="O")

       Student_ID Subject Homework_Completion_% Teacher_Comments
count       36468   36468                 36468            36468
unique      11580       6                     5            32918
top        S00476  Arabic                    95
freq           12    6224                  7453             3551

# Part 4: Data quality diagnosis

* Check missing values using both count and percentage.
* Check duplicates or logical duplicates.
* Check inconsistent categories.
* Check invalid, impossible, or out-of-range values.
* Create an issue log using the template below.

In [11]:
missing_count = df.isnull().sum()
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_df = pd.DataFrame({
    'Missing Count': missing_count,
    'Percentage (%)': missing_percentage
})
missing_df

                       Missing Count  Percentage (%)
Student_ID                         0             0.0
Subject                            0             0.0
Exam_Score                         0             0.0
Homework_Completion_%              0             0.0
Teacher_Comments                   0             0.0

**Kiểm tra lời phê của giáo viên**

In [12]:
empty_comments_count = (df['Teacher_Comments'].str.strip() == '').sum()
empty_comments_pct = (empty_comments_count / len(df)) * 100

print(f"Số dòng bị bỏ trống lời phê : {empty_comments_count} dòng")
print(f"Tỷ lệ thiếu: {empty_comments_pct:.2f}%")

Số dòng bị bỏ trống lời phê : 3551 dòng
Tỷ lệ thiếu: 9.74%

## Kiểm tra các giá trị ngoài phạm vi hợp lệ

In [13]:
# Kiểm tra trùng lặp logic theo cặp (Student_ID + Subject)
logical_dup_count = df.duplicated(subset=['Student_ID', 'Subject']).sum()
logical_dup_pct = (logical_dup_count / len(df)) * 100

print(f"Số bản ghi trùng lặp môn học của cùng một sinh viên: {logical_dup_count} dòng")
print(f"Tỷ lệ trùng lặp: {logical_dup_pct:.2f}%")

Số bản ghi trùng lặp môn học của cùng một sinh viên: 7732 dòng
Tỷ lệ trùng lặp: 21.20%

In [14]:
print(df['Homework_Completion_%'].value_counts())

Homework_Completion_%
95      7453
-5      7376
100%    7296
80%     7283
90      7060
Name: count, dtype: int64

In [15]:
print(df['Subject'].value_counts())

Subject
Arabic       6224
Science      6093
Geography    6082
English      6043
Math         6035
History      5991
Name: count, dtype: int64

In [16]:
df['Exam_Score'].agg(['min', 'max', 'mean', 'median', 'std'])

min        40.000000
max       110.000000
mean       74.964243
median     75.000000
std        20.538704
Name: Exam_Score, dtype: float64

In [17]:
scores_over_100 = df[df['Exam_Score'] > 100]
count_over_100 = len(scores_over_100)
pct_over_100 = (count_over_100 / len(df)) * 100
print(f"Số lượng bản ghi có điểm lớn hơn 100: {count_over_100} dòng")
print(f"Tỷ lệ phần trăm trên toàn bộ dữ liệu: {pct_over_100:.2f}%")

Số lượng bản ghi có điểm lớn hơn 100: 5139 dòng
Tỷ lệ phần trăm trên toàn bộ dữ liệu: 14.09%

# Part 5: Transformation and preparation

Chỉnh sửa cột lời phê của giáo viên

In [18]:
df['Teacher_Comments'] = df['Teacher_Comments'].str.strip()
df.loc[df['Teacher_Comments'] == '', 'Teacher_Comments'] = 'No comment'
print(f"Số dòng dính khoảng trắng sau xử lý: {(df['Teacher_Comments'] == '').sum()}")

Số dòng dính khoảng trắng sau xử lý: 0

Chỉnh sửa cột Subject

In [19]:
df['Subject'] = df['Subject'].astype('category')
print("Kiểu dữ liệu mới của cột Subject:", df['Subject'].dtype)

Kiểu dữ liệu mới của cột Subject: category

Chỉnh sửa cột Homework_Completion_%

In [20]:
df['Homework_Completion_%'] = df['Homework_Completion_%'].astype(str).str.replace('%', '', regex=False)
df['Homework_Completion_%'] = pd.to_numeric(df['Homework_Completion_%'], errors='coerce')

valid_homework_median = df[df['Homework_Completion_%'] >= 0]['Homework_Completion_%'].median()
print(f"Giá trị trung vị hợp lệ tính được: {valid_homework_median}%")

df.loc[df['Homework_Completion_%'] < 0, 'Homework_Completion_%'] = valid_homework_median

print("\nTần suất các giá trị sau khi làm sạch:")
print(df['Homework_Completion_%'].value_counts())

Giá trị trung vị hợp lệ tính được: 95.0%

Tần suất các giá trị sau khi làm sạch:
Homework_Completion_%
95     14829
100     7296
80      7283
90      7060
Name: count, dtype: int64

Chỉnh sửa cột Exam_Score

In [21]:
df['Exam_Score'] = df['Exam_Score'].clip(upper=100)

Giải quyết việc trùng ID và subject

In [22]:
# Sắp xếp giảm dần theo điểm thi để dòng điểm cao nhất lên đầu
df = df.sort_values(by=['Student_ID', 'Subject', 'Exam_Score'], ascending=[True, True, False])

# Chỉ giữ lại bản ghi điểm cao nhất cho mỗi cặp (Student_ID, Subject)
df_cleaned = df.drop_duplicates(subset=['Student_ID', 'Subject'], keep='first').copy()

df_cleaned = df_cleaned.reset_index(drop=True)
df_cleaned

,Student_ID,Subject,Exam_Score,Homework_Completion_%,Teacher_Comments
0,S00002,Arabic,69,95,Season end color son page their begin return t...
1,S00002,History,98,90,Sport beyond wait feel chair benefit section a...
2,S00003,History,63,95,Drive friend official house one approach troub...
3,S00004,English,100,95,Big everything sure identify happy church coun...
4,S00004,History,59,90,Recognize tell arrive toward collection contin...
...,...,...,...,...,...
28731,S12155,Geography,75,95,Mind every image stay owner third.
28732,S12155,History,96,100,Step campaign meeting yes build expert.
28733,S12155,Science,85,95,Word article different me just can arrive none...
28734,S12156,Math,76,95,Popular huge all someone address wrong young s...
28735,S12156,Science,56,100,House program already who wonder table sure mi...

In [23]:
df_cleaned['Exam_Status'] = np.where(df_cleaned['Exam_Score'] >= 50, 'Pass', 'Fail')

# Academic_Grade
def classify_grade(score):
    if score >= 90: return 'Excellent'
    elif score >= 80: return 'Good'
    elif score >= 65: return 'Average'
    elif score >= 50: return 'Below Average'
    else: return 'Weak'

df_cleaned['Academic_Grade'] = df_cleaned['Exam_Score'].apply(classify_grade)

# Nhóm mức độ hoàn thành bài tập (Homework_Effort_Group)
df_cleaned['Homework_Effort_Group'] = pd.cut(
    df_cleaned['Homework_Completion_%'],
    bins=[-1, 85, 95, 101],
    labels=['Low Effort', 'Medium Effort', 'High Effort']
)

# Cờ cảnh báo rủi ro học tập sớm (Academic_Risk_Flag)
# Gắn cờ 1 (Nguy cơ cao) nếu điểm thi < 50 VÀ tỷ lệ bài tập về nhà ở mức thấp (<= 85)
df_cleaned['Academic_Risk_Flag'] = np.where(
    (df_cleaned['Exam_Score'] < 50) & (df_cleaned['Homework_Completion_%'] <= 85), 
    1, 0
)
df_cleaned

,Student_ID,Subject,Exam_Score,Homework_Completion_%,Teacher_Comments,Exam_Status,Academic_Grade,Homework_Effort_Group,Academic_Risk_Flag
0,S00002,Arabic,69,95,Season end color son page their begin return t...,Pass,Average,Medium Effort,0
1,S00002,History,98,90,Sport beyond wait feel chair benefit section a...,Pass,Excellent,Medium Effort,0
2,S00003,History,63,95,Drive friend official house one approach troub...,Pass,Below Average,Medium Effort,0
3,S00004,English,100,95,Big everything sure identify happy church coun...,Pass,Excellent,Medium Effort,0
4,S00004,History,59,90,Recognize tell arrive toward collection contin...,Pass,Below Average,Medium Effort,0
...,...,...,...,...,...,...,...,...,...
28731,S12155,Geography,75,95,Mind every image stay owner third.,Pass,Average,Medium Effort,0
28732,S12155,History,96,100,Step campaign meeting yes build expert.,Pass,Excellent,High Effort,0
28733,S12155,Science,85,95,Word article different me just can arrive none...,Pass,Good,Medium Effort,0
28734,S12156,Math,76,95,Popular huge all someone address wrong young s...,Pass,Average,Medium Effort,0
28735,S12156,Science,56,100,House program already who wonder table sure mi...,Pass,Below Average,High Effort,0

Check lại sau khi sửa đổi

In [24]:
print(f"Kích thước cuối cùng của Dataset: {df_cleaned.shape[0]} dòng và {df_cleaned.shape[1]} cột.")
print(f"- Số lượng ô trống NaN: {df_cleaned.isnull().sum().sum()}")
print(f"- Số dòng dính giá trị điểm > 100: {len(df_cleaned[df_cleaned['Exam_Score'] > 100])}")
print(f"- Số dòng dính giá trị bài tập âm (<0): {len(df_cleaned[df_cleaned['Homework_Completion_%'] < 0])}")
print(f"- Số dòng trùng lặp logic còn sót lại: {df_cleaned.duplicated(subset=['Student_ID', 'Subject']).sum()}")
print(f"- Số dòng dính lỗi văn bản trống : {(df_cleaned['Teacher_Comments'].str.strip() == '').sum()}")

Kích thước cuối cùng của Dataset: 28736 dòng và 9 cột.
- Số lượng ô trống NaN: 0
- Số dòng dính giá trị điểm > 100: 0
- Số dòng dính giá trị bài tập âm (<0): 0
- Số dòng trùng lặp logic còn sót lại: 0
- Số dòng dính lỗi văn bản trống : 0

In [27]:

output_file_path = os.path.join(base_path, '..', 'data_cleaned', 'performance_cleaned.csv')

# Lấy đường dẫn thư mục cha để kiểm tra và tự động tạo nếu chưa có
output_dir = os.path.dirname(output_file_path)
if not os.path.exists(output_dir):
    os.makedirs(output_dir)
    print(f"Đã tạo thư mục mới: {output_dir}")

# Lưu dữ liệu sạch ra file
df_cleaned.to_csv(output_file_path, index=False, encoding='utf-8-sig')

print(f"🎉 Đã lưu dữ liệu sạch thành công tại: {output_file_path}")

🎉 Đã lưu dữ liệu sạch thành công tại: c:\Users\Admin\Desktop\Code\DHV301\Assignment\Assignment 1\code\..\data_cleaned\performance_cleaned.csv